version: 2.1

executors:
  nodejs:
      docker:
        - image: cimg/node:21.1.0

commands:
  checkout-and-restore-cache:
    description: "restore cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
  save-node-modules-cache:
    steps:
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  lint:
    executor: nodejs
    steps:
      - checkout-and-restore-cache
      - run: yarn install
      - save-node-modules-cache
      - run: yarn lint

  build:
    executor: nodejs
    steps:
      - checkout-and-restore-cache
      - run: yarn install
      - save-node-modules-cache
      - run: yarn build

  test:
    executor: nodejs
    steps:
      - checkout-and-restore-cache
      - run: yarn install
      - run: yarn build
      - run: yarn test --coverage

workflows:
  build-and-deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build